SignatureVerification/SignatureVerification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signatures/', include('signatures.urls')),
    path('', include('users.urls')),
    path('', include("projects.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SignatureVerification/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('sign-up/', views.sign_up, name='sign_up'),
    path("login/", views.log_in, name="login"),
    path("login-with-signature", views.login_with_signature,
         name='login_with_signature'),
    path("logout/", views.log_out, name="logout"),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('profile/history/', views.history, name='history'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('create-skill/', views.create_skill, name='create_skill'),
    path('edit-skill/<str:pk>/', views.edit_skill, name='edit_skill'),
    path('delete-skill/<str:pk>/', views.delete_skill, name='delete_skill'),
    path("inbox/",views.all_messages,name="inbox"),
    path("message/<str:id>",views.view_message,name="message"),
    path("send-message/<str:pk>/",views.create_message,name="create_message")
]

SignatureVerification/users/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=False,blank=True)
    first_name = models.CharField(max_length=200,blank=True,null=False)
    last_name=models.CharField(max_length=200,blank=True,null=False)
    username = models.CharField(max_length=200,blank=True,null=False)
    email=models.EmailField(null=False,blank=True,max_length=500)
    head_line=models.CharField(max_length=500,blank=True,null=False)
    bio=models.TextField(max_length=500,blank=True,null=False)
    location = models.CharField(max_length=200,null=True,blank=True)
    personal_signature = models.ImageField(upload_to='signatures/',blank=True,null=True,editable=True,default="signatures/default.png")
    picture = models.ImageField(upload_to='profiles/',blank=True,null=True,editable=True,default="profiles/avatar.png")
    national_id = models.CharField(blank=True,null=False,unique=True,max_length=100)
    github = models.CharField(max_length=500,null=True,blank=True)
    stackoverflow = models.CharField(max_length=500,null=True,blank=True)
    twitter = models.CharField(max_length=500,null=True,blank=True)
    linkedin = models.CharField(max_length=500,null=True,blank=True)
    personalwebsite = models.CharField(max_length=500,null=True,blank=True)

    id = models.UUIDField(default=uuid.uuid4,primary_key=True,unique=True,blank=False,editable=False,null=False)
    def __str__(self):
        return str(self.user.username)

class Skill(models.Model):
    name = models.CharField(null=False, blank=False, max_length=250)
    body = models.TextField(blank=True,null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    def __str__(self):
        return self.name[0:50]

class Message(models.Model):
    body = models.TextField(max_length=500)
    sender = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name="sender")
    reciever = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name="reciever")
    title = models.CharField(max_length=250,null=True,blank= True)
    is_read = models.BooleanField(default=False,null=True)
    created=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.body[0:50]

SignatureVerification/users/forms.py
from django.forms import ModelForm
from .models import Profile,Skill,Message
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class UpdateProfile(ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        exclude = ["user","username"]


class CreateUser(UserCreationForm):
    class Meta:
        model = User
        fields= ["username","email","password1","password2"]
        labels = {
            "username" : "UserName"
        }

class SkillCreation(ModelForm):
    class Meta:
        model=Skill
        fields=["name","body"]
    def __init__(self,*args,**kwargs):
        super(SkillCreation,self).__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs.update({"class":'input'})

class MessageCreation(ModelForm):
    class Meta:
        model=Message
        fields = ["title","body"]
    def __init__(self,*args,**kwargs):
        super(MessageCreation,self).__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs.update({"class":"input"})

SignatureVerification/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Profile,Skill,Message
from django.conf import settings
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .forms import UpdateProfile, CreateUser , SkillCreation , MessageCreation
from django.contrib.auth.models import User
from signatures.views import siamese_model, Verify, preprocess
from django.contrib import messages
from projects.models import Project
from signatures.models import Signature

def sign_up(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged in")
        return redirect("profiles")
    form = CreateUser()
    if request.method == "POST":
        form = CreateUser(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user=user)
            return redirect("update_profile")
        else:
            return HttpResponse("Invalid Request")
    context = {"form": form}
    return render(request, "users/signup.html", context)

@login_required(login_url="login")
def update_profile(request):
    try:
        profile = request.user.profile
    except:
        messages.error("Profile Not Found")
        return redirect("login")
    form = UpdateProfile(instance=profile)
    if request.method == "POST":
        form = UpdateProfile(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
        messages.success(request, "Profile Saved")
        return redirect("profiles")
    context = {"form": form}
    return render(request, 'users/update_profile.html', context)

@login_required(login_url="login")
def log_out(request):
    try:
        user = request.user
    except:
        messages.error(request, "An error occured")
    logout(request=request)
    messages.success(request, "Logged out successfully")
    return redirect("profiles")

def log_in(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged in")
        return redirect("profiles")
    if request.method == "POST":
        try:
            password = request.POST["password"]
            email = request.POST["email"]
            username = request.POST["username"]
        except:
            return HttpResponse("Invalid Request")
        user = authenticate(request, username=username, password=password)
        print(user)
        if user:
            login(request, user=user)
            messages.success(request, "logged in successfuly")
            return redirect("profiles")
        else:
            messages.error(request, "Username or Password is incorrect")
            return HttpResponse("Invalid Account")
    context = {}
    return render(request, 'users/login.html', context)

def login_with_signature(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged in")
        return redirect("profiles")
    if request.method == "POST":
        try:
            username = request.POST["username"]
            user = User.objects.get(username=username)
        except:
            messages.error(request, "Account Not Found")
            return redirect("login")
        try:
            image = request.FILES["signature"]
        except:
            messages.error(request, "Invalid Image")
            return redirect("login")
        try:
            if user.profile.personal_signature.name == "":
                messages.error(request, "Invalid personal signature Image")
                return redirect("login_with_signature")
            verify = Verify.objects.create(
                owner=user.profile, first_signature=user.profile.personal_signature, second_signature=image)
        except:
            messages.error(request, "Profile signature Image is not Found")
            return redirect("login")
        first_signature = preprocess(verify.first_signature)
        second_signature = preprocess(verify.second_signature)
        prediction = siamese_model.predict((first_signature, second_signature))
        print(prediction)
        if prediction >= 0.7:
            prediction = "Valid"
            verify.prediction = prediction
            verify.save()
            login(request, user=user)
            messages.success(request, "Logged In Successfully")
            return redirect("profiles")
        else:
            prediction = "Invalid"
            verify.prediction = prediction
            verify.save()
            messages.error(request, "Incorrect Signature")
            return redirect("login")
    context = {}
    return render(request, 'users/login_with_signature.html', context)

# Create your views here.

def profiles(request):
    profiles = Profile.objects.all()
    context = {"profiles": profiles}
    return render(request, "users/profiles.html", context)

def profile(request, pk):
    try:
        profile = Profile.objects.get(id=pk)
    except:
        return HttpResponse("Profile Not Found")
    projects = Project.objects.filter(owner=profile)
    if request.user.profile == profile:
        signatures = Signature.objects.filter(owner=profile)
    else:
        signatures=[]
    context = {"profile": profile,
               "signatures": signatures, "projects": projects}
    return render(request, "users/profile.html", context)

def history(request):
    try:
        profile = request.user.profile
    except:
        return HttpResponse("Profile Not Found")
    verify_objects = profile.verify_set.all()
    context = {"verify_objects": verify_objects}
    return render(request, 'users/history.html', context)

@login_required(login_url="login")
def create_skill(request):
    profile = Profile.objects.get(user=request.user)
    form = SkillCreation()
    if request.method == "POST":
        form = SkillCreation(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner=profile
            skill.save()
            messages.success(request,"Skill added successfuly")
            return redirect("profile",profile.id)
        else:
            messages.error(request,"Invalid skill information")
    context={"form":form}
    return render(request,"users/create_skill.html",context)

@login_required(login_url="login")
def delete_skill(request,pk):
    skill=Skill.objects.get(pk=pk)
    profile = skill.owner
    if request.method=="POST":
        if request.user==profile.user:
            skill.delete()
            messages.success(request,"Skill deleted successfully")
            return redirect('profile',profile.id)
        else:
            messages.error(request,"You are not the owner")
            return redirect('profile',profile.id)
    context={"skill":skill,"value":"delete"}
    return render(request,"users/create_skill.html",context)

@login_required(login_url="login")
def edit_skill(request,pk):
    skill=Skill.objects.get(pk=pk)
    form = SkillCreation(instance=skill)
    profile=skill.owner
    if request.method=="POST" and request.user==profile.user:
        form = SkillCreation(request.POST,instance=skill)
        if form.is_valid():
            skill=form.save(commit=False)
            skill.owner=profile
            skill.save()
            messages.success(request,"Skill edited successfully")
            return redirect("profile",profile.id)
        else:
            messages.error(request,"Invalid skill Information")

    context={"form":form}
    return render(request,"users/create_skill.html",context)

@login_required(login_url="login")
def all_messages(request):
    profile = request.user.profile
    receieved_messages=Message.objects.filter(reciever=profile)
    sent_messages = Message.objects.filter(sender=profile)
    unread_length=0
    for message in receieved_messages:
        if message.is_read==False:
            unread_length+=1
    print(sent_messages)
    context={"sent_messages":sent_messages,"receieved_messages":receieved_messages,"unread_length":unread_length}
    return render(request,"users/inbox.html",context)


@login_required(login_url="login")
def view_message(request,id):
    try:
        message = Message.objects.get(id=id)
        if message.reciever != request.user.profile and message.sender != request.user.profile:
            messages.error(request,"Access Denied")
            return redirect("inbox")
        if message.is_read==False:
            message.is_read=True
            message.save()
    except:
            messages.error(request,"Message Not Found")
            return redirect("inbox")
    context={"message":message}
    return render(request,"users/message.html",context)


@login_required(login_url="login")
def create_message(request,pk):
    sender=request.user.profile
    try:
        reciever = Profile.objects.get(id=pk)
    except:
        messages.error("Reciever not found")
        return redirect("profiles")
    form = MessageCreation()
    if request.method=="POST":
        message = form.save(commit=False)
        message.reciever = reciever
        message.sender = sender
        message.save()
    context={"form":form}
    return render(request,"users/create_message.html",context)    

SignatureVerification/users/templates/users/create_message.html
{%extends 'home.html'%} {%block content%}

<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{%url 'profiles'%}"><</a>
      <br />

      <form class="form" method="POST" enctype="multipart/form-data">
        {%csrf_token%} {%for element in form%}
         <div class="form__field">
                        <label for="formInput#text">{{element.label}} </label>
                        {{element}}

        {%endfor%}
        {%if value == "delete"%}
          <p>Are you sure you want to delete this skill ?</p>
        {%endif%}
        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>

{%endblock%}

SignatureVerification/users/templates/users/create_skill.html
{%extends 'home.html'%} {%block content%}

<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{%url 'profiles'%}"><</a>
      <br />

      <form class="form" method="POST" enctype="multipart/form-data">
        {%csrf_token%} {%for element in form%}
         <div class="form__field">
                        <label for="formInput#text">{{element.label}} </label>
                        {{element}}

        {%endfor%}
        {%if value == "delete"%}
          <p>Are you sure you want to delete this skill ?</p>
        {%endif%}
        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>

{%endblock%}

SignatureVerification/users/templates/users/history.html
{%extends 'home.html' %} {%load static%} {%block content%} 
    <main class="projects">
        <section class="hero-section text-center">
            <div class="container container--narrow">
                <div class="hero-section__box">
                    <h2><span> Signatures Verification </span></h2>
                </div>
            </div>
        </section>
        <section class="projectsList">
            <div class="container">
                <div class="grid grid--three">
                    {%for object in verify_objects%}
    
                    <div class="column">
                        <div class="card project" style="height: 800px;">
                            <div style="text-align: center; height: 40%;"><img class="project__thumbnail" style="width: 100%;" src="{{object.first_signature.url}}" alt="project thumbnail" /></div>
                            <div style="text-align: center; height: 40%;">
                            <img class="project__thumbnail" style="width: 100%;" src="{{object.second_signature.url}}" alt="project thumbnail" />
                            </div>

                                <div class="card__body">
                                    <h3 class="project__title">{{object.prediction}}</h3>
                                    <p>
                                        {{object.created |timesince}} 
                                    </p>
                                </div>
                            </a>
                        </div>
                    </div>
                    {%endfor%}
                </div>
            </div>
        </section>
    
        <div class="pagination">
            <ul class="container">
                <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
                <li><a href="#" class="btn btn--sub">01</a></li>
                <li><a href="#" class="btn">02</a></li>
                <li><a href="#" class="btn">03</a></li>
                <li><a href="#" class="btn">04</a></li>
                <li><a href="#" class="btn">05</a></li>
                <li><a href="#" class="btn">06</a></li>
                <li><a href="#" class="btn">07</a></li>
                <li><a href="#" class="btn">08</a></li>
                <li><a href="#" class="btn">09</a></li>
                <li><a href="#" class="btn">10</a></li>
                <li><a href="#" class="btn">Next &#10095;</a></li>
            </ul>
        </div>

 {%endblock content%}

SignatureVerification/users/templates/users/inbox.html
{%extends "home.html"%} {%block content%}
<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">Recieved(<span>{{unread_length}}</span>)</h3>
    <ul class="messages message--unread">
      {%for message in receieved_messages%}
      <li class="message {%if not message.is_read%}message--unread{%endif%}">
        <a href="{%url 'message' message.id%}">
          <span class="message__author">from {{message.sender.user.username}}</span>
          <span class="message__subject">{{message.title}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>
      {%endfor%}
      
      <h2>Sent<h2>
      {%for message in sent_messages%}
      <li class="message">
        <a href="{%url 'message' message.id%}">
          <span class="message__author">to {{message.reciever.user.username}}</span>
          <span class="message__subject">{{message.title}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>
      {%endfor%}
    </ul>
  </div>
  {%endblock%}
</main>

SignatureVerification/users/templates/users/login.html
{%extends 'home.html'%} {%load static%} {%block content%}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{%static 'images/icon.svg'%}" alt="icon" />
      </a>
      <h3>Account Login</h3>
      <p>Hello Developer, Welcome Back!</p>
    </div>
    <form enctype="multipart/form-data" method="POST">
      {%csrf_token%}
      <!-- Input:Email -->
      <div class="form__field">
        <label for="formInput#text">email: </label>
        <input
          class="input input--text"
          id="formInput#text"
          type="email"
          name="email"
          placeholder="Enter your Email..."
        />
      </div>

      <!-- Input:username -->
      <div class="form__field">
        <label for="formInput#text">Username: </label>
        <input
          class="input input--text"
          id="formInput#text"
          type="text"
          name="username"
          placeholder="Enter your username..."
        />
      </div>

      <!-- Input:Password -->
      <div class="form__field">
        <label for="formInput#password">Password: </label>
        <input
          class="input input--password"
          id="formInput#passowrd"
          type="password"
          name="password"
          placeholder="••••••••"
        />
      </div>

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
        <a href="forgetpassword.html">Forget Password?</a>

      </form>
      </div>
      
          <div class="auth__alternative">
            <a href="{%url 'login_with_signature'%}">Login With Signature</a>
            <p>Don’t have an Account?</p>
      <a href="{%url 'sign_up'%}">Sign Up</a>
    </div>
  </div>
</div>
    {%endblock content%}

SignatureVerification/users/templates/users/profile.html
{%extends 'home.html'%}
{%load static%}
{%block content%}

  <!-- Main Section -->
  <main class="profile my-md">
    <d class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              {%if profile.picture%}
              <img class="avatar avatar--xl" src="{{profile.picture.url}}" />
              {% endif %}
              <h2 class="dev__name">{{profile.username}}</h2>
              <p class="dev__title">{{profile.headline}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">
                {%if profile.github %}
                <li>
                  <a title="Github" href="{{profile.github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {%endif%}

                {%if project.stackoverflow%}
                <li>
                  <a title="Stackoverflow" href="{{profile.stackoverflow}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {%endif%}

                {%if profile.twitter%}
                <li>
                  <a title="Twitter" href="{{profile.twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {%endif%}

                {%if profile.linkedin%}

                <li>
                  <a title="LinkedIn" href="{{profile.linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {%endif%}

                {%if profile.personalwebsite%}
                <li>
                  <a title="{{profile.personalwebsite}}" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {%endif%}

              </ul>
              {%if request.user.profile != profile%}
              <a href="{%url 'create_message' profile.id%}" class="btn btn--sub btn--lg">Send Message </a>
              {%endif%}
            </div>
              {%if request.user.profile == profile%}
              <a style='margin-bottom:30px;' href="{%url 'update_profile' %}" class="btn btn--primary btn--lg">Update Profile </a>
              {%endif%}
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {%if request.user.profile == profile%}
              <a style='margin-bottom:30px;' href="{%url 'create_skill' %}" class="btn btn--primary btn--lg">Add Skill </a>
              {%endif%}
          {%for skill in profile.skill_set.all %}
             {%if skill.body%}
<div class="devSkill">
  <h4 class="devSkill__title">{{skill.name}}</h4>
  <p class="devSkill__info">
    {{skill.body}}
  </p>
</div>
{%if request.user.profile == profile%}
  <a href="{%url 'edit_skill' skill.id%}">Edit Skill</a>
  <a href="{%url 'delete_skill' skill.id%}">Delete Skill</a>
{%endif%}
             {%endif%}
              {%endfor%}
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
              {%for skill in profile.skill_set.all %}
              {%if skill.body == ''%}
                  <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill.name}}</small>
                </span>
{%if request.user.profile == profile%}
  <a href="{%url 'edit_skill' skill.id%}">Edit Skill</a>
  <br>
{%endif%}
              {%endif%}
              {%endfor%}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              {%for project in projects%}
              <div class="column">
                <div class="card project" style="text-align:center;">
                  <a href="{%url 'project' project.id%}" class="project">
                    <img style="width:100%; height:400px; object-fit:cover;" src="{{project.image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{%url 'profile' project.owner.id%}">{{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.votes}} Votes)
                      </p>
                      <div class="project__tags">
                     {%for tag in project.tags.all%}
                       
                  <span class="tag tag--pill tag--main">
                    <small>{{tag.name}}</small>
                  </span>
                     {%endfor%}
                      </div>
                    </div>
                  </a>
                </div>
              
              </div>
              {%endfor%}

            </div>
          </div>

          {%if signatures%}

            <div class="devInfo">
            <h3 class="devInfo__title">Signatures</h3>
            <div class="grid grid--two">
              
              {%for signature in signatures%}
              <div class="column">
                <div class="card project" style="text-align:center;">
                  <a href="{%url 'signature' signature.id%}" class="project">
                    <img style="width:100%;" class="project__thumbnail" src="{{signature.image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{signature.title}}</h3>
                      <p><a class="project__author" href="{%url 'profile' signature.owner.id%}">{{signature.owner.name}}</a></p>
                      <div class="project__tags">
                     {%for tag in signature.tags.all%}
                       
                  <span class="tag tag--pill tag--main">
                    <small>{{tag.name}}</small>
                  </span>
                     {%endfor%}
                      </div>
                    </div>
                  </a>
                </div>
              
              </div>
              {%endfor%}

            </div>
          </div>
          {%endif%}
        </div>
      </div>
    </div>
  </div>
  </
  </main>

  {%endblock %}
</main>

SignatureVerification/users/templates/users/profiles.html
{%extends 'home.html' %} {%load static%} {%block content%}

<!-- Main Section -->
<main class="home">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
        <h2>FROM AROUND THE WORLD</h2>
      </div>

      <div class="hero-section__search">
        <form class="form" action="#" method="get">
          <div class="form__field">
            <label for="formInput#search">Search Developers </label>
            <input
              class="input input--text"
              id="formInput#search"
              type="text"
              name="text"
              placeholder="Search by developer name"
            />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>

  <section class="devlist">
    <div class="container">
      <div class="grid grid--three">
  {%for profile in profiles%}
        <div class="column card">
          <div class="dev">
            <a href="{%url 'profile' profile.id%}" class="card__body">
              <div class="dev__profile">
              {%if profile.picture%}

                <img
                  class="avatar avatar--md"
                  src="{{profile.picture.url}}"
                  alt="image"
                />
                
              {% endif %}

                <div class="dev__meta">
                  <h3>{{profile.username}}</h3>
                  <h5>{{profile.head_line}}</h5>
                  <h6>{{profile.location}}</h6>
                </div>
              </div>
              <p class="dev__info">
                {{profile.bio}}
              </p>
              <div class="dev__skills">

              {%for skill in profile.skill_set.all %}
                <span class="tag tag--pill tag--main">
                  <small>{{skill.name}}</small>
                </span>
              {%endfor%}
              </div>

            </a>

          </div>
        </div>
  {%endfor%}
    
      </div>
    </div>
  </section>
  
  <div class="pagination">
    <ul class="container">
      <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
      <li><a href="#" class="btn btn--sub">01</a></li>
      <li><a href="#" class="btn">02</a></li>
      <li><a href="#" class="btn">03</a></li>
      <li><a href="#" class="btn">04</a></li>
      <li><a href="#" class="btn">05</a></li>
      <li><a href="#" class="btn">06</a></li>
      <li><a href="#" class="btn">07</a></li>
      <li><a href="#" class="btn">08</a></li>
      <li><a href="#" class="btn">09</a></li>
      <li><a href="#" class="btn">10</a></li>
      <li><a href="#" class="btn">Next &#10095;</a></li>
    </ul>
  </div>
</main>

  </div>

 {%endblock content%}
  <!-- Search Result: DevList -->